### ISSUE TITLE
Route with name "login" not found

### ISSUE THREAD

**Issue by adarshkhatri** [coolcsn/CsnAuthorization#14]
Hi

I have installed all it's dependancies.

I get this error when I activate this module and go to "editProfile, resetPassword" etc action. I believe something is wrong in "RegistrationController.php". I can confirm login, signup is working. However after clicking on confirmation email, it was taking me to home page, so I had to update db manually.

Fatal error: Uncaught exception 'Zend\Mvc\Router\Exception\RuntimeException' with message 'Route with name "login" not found' in /Applications/XAMPP/xamppfiles/htdocs/skeleton/vendor/zendframework/zend-mvc/src/Router/Http/TreeRouteStack.php:317 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/skeleton/vendor/coolcsn/csn-authorization/src/CsnAuthorization/Module.php(64): Zend\Mvc\Router\Http\TreeRouteStack->assemble(Array, Array) #1 [internal function]: CsnAuthorization\Module->onRoute(Object(Zend\Mvc\MvcEvent)) #2 /Applications/XAMPP/xamppfiles/htdocs/skeleton/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #3 /Applications/XAMPP/xamppfiles/htdocs/skeleton/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('route', Object(Zend\Mvc\MvcEvent), Object(Closure)) #4 /Applications/XAMPP/xamppfiles/htdocs/skeleton/vendor/zendframework/zend-mvc/src/Application.php(297): Zend\EventManager\EventMan in /Applications/XAMPP/xamppfiles/htdocs/skeleton/vendor/zendframework/zend-mvc/src/Router/Http/TreeRouteStack.php on line 317

Please suggest.

**Comment by wingman007** [comment]
Make sure route "login" exists. Define it in CsnUser module.config.php for example.

**Comment by adarshkhatri** [comment]
It does exist.

The error is because of this:

'acl' => array(
        /**
         \* By default the ACL is stored in this config file.
         \* If you activate the database_storage ACL will be constructed from the database via Doctrine
         \* and the roles and resources defined in this config wil be ignored.
         \* 
         \* Defaults to false.
         _/
        'use_database_storage' => false,
        /_*
         \* The route where users are redirected if access is denied.
         \* Set to empty array to disable redirection.
         */
        'redirect_route' => array(
            'params' => array(
                //'controller' => 'my_controllet',
                //'action' => 'my_action',
                //'id' => '1',
            ),
            'options' => array(
                'name' => 'login', 
            ),
        ),

in CsnAuthorization/config/acl.global.php file.

Not sure what is happening.

**Comment by wingman007** [comment]
Thank you very much for the information. I will try to figure out what is going on.

**Comment by adarshkhatri** [comment]
Any luck?

**Comment by wingman007** [comment]
I think the route ... 'name' => 'login', ... is missing in the modules. If you have not installed CsnUser you probably don't have 'login' route. So the solutions are:
1. Define in one of your modules a route with a name 'login'
2. Change the rout definition in CsnAuthorization/config/acl.global.php 'redirect_route' => array(
'params' => array(
//'controller' => 'my_controllet',
//'action' => 'my_action',
//'id' => '1',
),
'options' => array(
'name' => 'login', 
),
),

and redirect to another existing route

**Comment by adarshkhatri** [comment]
I can confirm I have installed CsnUser and also can confirm that I am able to do signup and login successfully.

This works only when I disable CsnAuthorization.

**Comment by adarshkhatri** [comment]
changing this worked for me, but not sure what's exactly happening;

'redirect_route' => array(
            'params' => array(
                'controller' => 'CsnUser\Controller\Index',
                'action' => 'login',
                'id' => '1',
            ),
            'options' => array(
                'name' => 'user-index'
            ),
        ),

**Comment by wingman007** [comment]
1. Authorization is a tricky one. The usual problems are:
   1.1. Redirecting to a route which doesn't exist (e.g. 'login', but login has not been defined in any module)
   1.2. Redirecting to a resource for which the user doesn't have enough privileges to reach. In this case we get circular redirection (endless loop).

For the first problem you will get an exception message from Zend.
For the second problem the browser will warn you that the page redirects in endless loop.
1. What is happening?
   You have a choice to redirect to a controller and action and even sending an argument id=1
   or
   You redirect to a defined route

2.1. This is how I do it in one of our real projects (acl.global.php):
        'redirect_route' => array(
            'params' => array(
                //'controller' => 'my_controllet',
                //'action' => 'my_action',
                //'id' => '1',
            ),
            'options' => array(
                // 'name' => 'login', 
                'name' => 'home', // the name of the rout
            ),

As you can see I don't use a controller and action instead I am redirecting to a route I have defined in one of my modules.

And down in the configuration (acl.global.php) I made sure the controller and action to which 'home' leads are accessible by everyone!

2.2. My 'home' route for this particular project has been defined in CsnCms module (module.config.php) and leads to module 'CsnCms' controller  'Index' action 'front-page'
...
'router' => array(
        // I am replacing the original route from Application here
        'routes' => array(
            'home' => array(
                'type' => 'Zend\Mvc\Router\Http\Literal',
                'options' => array(
                    'route'    => '/',
                    'defaults' => array(
                        '**NAMESPACE**' => 'CsnCms\Controller',
                        'controller'    => 'Index',
                        'action'        => 'front-page',
                    ),
                ),
            ),
...

2.3. Now when I know where I am redirecting everyone I have to make sure this resource (controller, action) is accessible by everyone in the file 'acl.global.php'
...
'CsnCms\Controller\Index' => array(
//                      'all' => 'guest'
                    'index' => 'guest',
                    'front-page' => 'guest', // SUPER important 
                ),
...

As you can see I marked with '// SUPER important' . The page I am redirecting to is accessible by every user of the system.

I hope this helps! :)
Chears!

**Comment by coolcsn** [comment]
1. Authorization is a tricky one. The usual problems are:
   1.1. Redirecting to a route which doesn't exist (e.g. 'login', but login
   has not been defined in any module)
   1.2. Redirecting to a resource for which the user doesn't have enough
   privileges to reach. In this case we get circular redirection (endless
   loop).

For the first problem you will get an exception message from Zend.
For the second problem the browser will warn you that the page redirects in
endless loop.
1. What is happening?
   You have a choice to redirect to a controller and action and even sending
   an argument id=1
   or
   You redirect to a defined route

2.1. This is how I do it in one of our real projects (acl.global.php):
        'redirect_route' => array(
            'params' => array(
                //'controller' => 'my_controllet',
                //'action' => 'my_action',
                //'id' => '1',
            ),
            'options' => array(
                // 'name' => 'login',
'name' => 'home', // the name of the rout
            ),

As you can see I don't use a controller and action instead I am redirecting
to a route I have defined in one of my modules.

And down in the configuration (acl.global.php) I made sure the controller
and action to which 'home' leads are accessible by everyone!

2.2. My 'home' route for this particular project has been defined in CsnCms
module (module.config.php) and leads to module 'CsnCms' controller  'Index'
action 'front-page'
...
'router' => array(
// I am replacing the original route from Application here
        'routes' => array(
            'home' => array(
                'type' => 'Zend\Mvc\Router\Http\Literal',
                'options' => array(
                    'route'    => '/',
                    'defaults' => array(
                        '**NAMESPACE**' => 'CsnCms\Controller',
                        'controller'    => 'Index',
                        'action'        => 'front-page',
                    ),
                ),
            ),
...

2.3. Now when I know where I am redirecting everyone I have to make sure
this resource (controller, action) is accessible by everyone in the file
'acl.global.php'
...
'CsnCms\Controller\Index' => array(
// 'all' => 'guest'
'index' => 'guest',
'front-page' => 'guest', // SUPER important
),
...

As you can see I marked with '// SUPER important' . The page I am
redirecting to is accessible by every user of the system.

I hope this helps! :)
Chears!

**Comment by adarshkhatri** [comment]
Thank you for brief explanation.

The problem existed on authorisation indeed, however in allow access section I had to change as following for "editProfileAction":

'edit-profile' => 'member' // 'editProfile' => 'member' was not working.

Thank you again.

**Comment by adarshkhatri** [comment]
One more question, can we also print "Access denied" message after redirection?

**Comment by wingman007** [comment]
Yes. I use to redirect to an action where I am displaying the message "Access denied", in one of my old projects. I don't like this anymore. I silently redirect to the index or login page in my recent projects without giving the information "Access denied". It is up to you to decide.
