### ISSUE TITLE
How to hide Edit Profile button for guest?

### ISSUE THREAD

**Issue by dennis-fedco** [coolcsn/CsnAuthorization#3]
Currently the "Edit Profile" button on shows up for guest, member and admin.

I want to hide it for guest.  Is there a way I can do this?

**Comment by revov** [comment]
This issue is connected to the **CsnUser** module and has nothing to do with Authorization. However you can disable the navigation menu from the configuration of **CsnUser** (check the [readme](https://github.com/coolcsn/CsnUser)) and implement your own navigation, for example, using **CsnAclNavigation**.

**Comment by dennis-fedco** [comment]
Thanks ... My issue is not connected to navigation.  I picked navigation because it is an existing element and I thought it will be easy to use.

To rephrase, I want to show or hide an element on the page, based on permissions, and was wondering if there was a way to do so.  For example for a member I want to display "You are a member".  For an admin I want to say "You are an admin".  I don't know how to do this.

**Comment by revov** [comment]
`$this->identity()` in a controller or viewScript returns the current user. If you assign it to let's say `$user`, then you can call `$user->getRole()->getName()` to get the name of the Role. Once you have the $roleName you can get the ACL from $serviceLocator->get('acl') and use it's isAllowed($roleName , $resource, $privilege) method.
_Expect a viewHelper soon that will allow you to do this in one step._

**EDIT:** A view helper and a controller plugin have been implemented to suit your needs. In your controllers or view scripts you can call `$this->isAllowed($resource, $privilege)` to check whether the current user has access to a resource.

**Comment by dennis-fedco** [comment]
Thank You!  A view helper helped!  I was able to do what I wanted to do.
